name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Change to 'master' if that's your source branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches the archie theme submodule
          fetch-depth: 0    # Fetch all history for proper git submodule handling

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # This tells the action to push the public folder to the 'gh-pages' branch
          publish_branch: gh-pages